# -*- coding: utf-8 -*-
"""visDrone_YOLO.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12Iflp0R05DnRgqxpNECPjyxT7Ld5ejX-
"""

from PIL import Image
import os
import numpy as np

annotations_dir = "/home/oykus/Documents/yolov3/datasets/VisDrone2019-DET-train/annotations"
all_files = os.listdir(annotations_dir)
newlines=[]
for i in range(len(all_files)):
    annotationLines = open("/home/oykus/Documents/yolov3/datasets/VisDrone2019-DET-train/annotations/"+all_files[i], "r")
    im = Image.open("/home/oykus/Documents/yolov3/datasets/VisDrone2019-DET-train/images/"+all_files[i].rstrip(".txt")+".jpg","r")
    width, height = im.size
    for line in annotationLines:
        line = line.rstrip('\n')
        line = line.split(",")

        x_top= int(line[0])
        y_top=int(line[1])
        w=float(line[2])
        h=float(line[3])

        x_center= float((x_top+float(w/2))/width)
        y_center=float((y_top-float(h/2))/height)
        w=float(w/width)
        h=float(h/height)
        newline =str(line[5]) + "," + str(x_center) + "," + str(y_center) + "," + str(w) + "," + str(h)
        f = open("/home/oykus/Documents/yolov3/datasets/VisDrone2019-DET-train/annotations/darknet53_annotations/"+all_files[i], "w+")
        f.write(newline + '\n')
