# -*- coding: utf-8 -*-
"""visDrone_YOLO.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12Iflp0R05DnRgqxpNECPjyxT7Ld5ejX-
"""

from PIL import Image
import os
import numpy as np

annotations_dir = "/content/gdrive/My Drive/Colab Notebooks/sample_data/toTrain/sample_data/annotations"
all_files = os.listdir(annotations_dir)
newlines=[]
for i in range(len(all_files)):
  print(all_files[i])
  annotationLines = open("/content/gdrive/My Drive/Colab Notebooks/sample_data/toTrain/sample_data/annotations/"+all_files[i], "r")
  im = Image.open("/content/gdrive/My Drive/Colab Notebooks/sample_data/toTrain/sample_data/"+all_files[i].rstrip(".txt")+".jpg","r")
  width, height = im.size
  for line in annotationLines:
    line = line.rstrip('\n')
    line = line.split(",") 
    
    x_top= int(line[0])
    y_top=int(line[1])
    w=int(line[2])
    h=int(line[3])

    x_center=(x_top+w/2)/width
    y_center=(y_top-h/2)/height
    newline = (line[5], x_center,y_center,w/width,h/height)
    newlines.append(newline)

